from django.db import models


class SampleType(models.TextChoices):
    ACID = 'acid', 'Acid'
    BASE = 'base', 'Base'
    BUFFER = 'buffer', 'Buffer'
    NEUTRAL = 'neutral', 'Neutral'
    UNKNOWN = 'unknown', 'Unknown'

class ChemicalSample(models.Model):
    """
    Core record for a chemical sample measurement
    
    Design rules:
    -concentration is fixed to mol/L
    -temperature defaults to None, 25°C is assumed in analysis if absent
    -recorded_at is autogenerated
    -sample_name is NOT unique
    """

    sample_name = models.CharField(
        max_length=100,
        help_text="Follow convention: TYPE-NUMBER-INITIALS (e.g BUF-001-AK)"
    )

    sample_type = models.CharField(
        max_length=10,
        choices=SampleType.choices,
        help_text="Chemical classification of the sample"
    )

    pH = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        help_text="pH value (0.00 - 14.00)" 
    )

    concentration = models.DecimalField(
        max_digits=8,
        decimal_places=4,
        help_text="Concentration in mol/L (molarity). Unit is fixed, do not convert."
    )

    temperature = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Termperature in °C at time of measurement. Assumed 25°C if blank."
    )

    notes = models.TextField(
        blank=True,
        default='',
        help_text="Free-text observations. Max 500 characters."
    )
    recorded_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Auto-generated UTC timestamp. Never set manually"
    )

    class Meta:
        ordering = ['-recorded_at']
        verbose_name = 'Chemical Sample'
        verbose_name_plural = 'Chemical Samples'

    def __str__(self):
        return f"{self.sample_name} | {self.sample_type} | pH {self.pH} | concentration {self.concentration}"