# Generated by Django 6.0.1 on 2026-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(help_text='Follow convention: TYPE-NUMBER-INITIALS (e.g BUF-001-AK)', max_length=100)),
                ('sample_type', models.CharField(choices=[('acid', 'Acid'), ('base', 'Base'), ('buffer', 'Buffer'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], help_text='Chemical classification of the sample', max_length=10)),
                ('pH', models.DecimalField(decimal_places=2, help_text='pH value (0.00 - 14.00)', max_digits=4)),
                ('concentration', models.DecimalField(decimal_places=4, help_text='Concentration in mol/L (molarity). Unit is fixed, do not convert.', max_digits=8)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Termperature in °C at time of measurement. Assumed 25°C if blank.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-text observations. Max 500 characters.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Auto-generated UTC timestamp. Never set manually')),
            ],
            options={
                'verbose_name': 'Chemical Sample',
                'verbose_name_plural': 'Chemical Samples',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
